package main

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

type Version struct {
	Tag         string
	Description string
	Generator   string
}

func main() {
	versions, err := getVersionsFromGitTags()
	if err != nil {
		slog.Error("Failed to get versions from git tags", "error", err)
		os.Exit(1)
	}

	if err := generateReleaseGo(versions); err != nil {
		slog.Error("Failed to generate profile releases", "error", err)
		os.Exit(1)
	}

	if err := generateBuildinfoGo(); err != nil {
		slog.Error("Failed to generate buildinfo", "error", err)
		os.Exit(1)
	}

	slog.Info("Successfully generated internal/profile/releases_generated.go and internal/buildinfo/buildinfo_generated.go")
}

func getVersionsFromGitTags() ([]Version, error) {
	// Get list of all generator functions from source files
	generators, err := getKnownGenerators()
	if err != nil {
		return nil, fmt.Errorf("failed to get known generators: %w", err)
	}

	// --sort=-v:refname ensures tags are sorted by version (newest is first!)
	cmd := exec.Command(
		"git",
		"tag",
		"-l",
		"--sort=-v:refname",
		"--format=%(refname:short) %(contents:subject)",
		"v[0-9]*.[0-9]*.[0-9]*",
	)
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git tag command failed: %w", err)
	}

	var versions []Version
	for _, line := range strings.Split(strings.TrimSpace(string(output)), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}

		parts := strings.SplitN(line, " ", 2)
		tag := parts[0]
		if tag == "" {
			continue
		}
		desc := ""
		if len(parts) > 1 {
			desc = strings.TrimSpace(parts[1])
		}

		generator := genName(tag)

		// Only include versions that have a known generator function
		if !generators[generator] {
			slog.Warn("Skipping tag with unknown generator", "tag", tag, "generator", generator)
			continue
		}

		versions = append(versions, Version{
			Tag:         tag,
			Description: desc,
			Generator:   generator,
		})
	}

	return versions, nil
}

// getKnownGenerators scans internal/profile/ files and finds all generateV*Default functions
func getKnownGenerators() (map[string]bool, error) {
	generators := make(map[string]bool)

	rootDir, err := findProjectRoot()
	if err != nil {
		return nil, err
	}

	files, err := filepath.Glob(filepath.Join(rootDir, "internal", "profile", "*.go"))
	if err != nil {
		return nil, err
	}

	for _, file := range files {
		data, err := os.ReadFile(file)
		if err != nil {
			continue
		}

		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "func generateV") {
				parts := strings.Fields(line)
				if len(parts) >= 2 {
					funcName := parts[1]
					if idx := strings.Index(funcName, "("); idx != -1 {
						funcName = funcName[:idx]
					}
					// Only include functions ending with "Default" (exclude generateV107Like etc.)
					if strings.HasSuffix(funcName, "Default") {
						generators[funcName] = true
					}
				}
			}
		}
	}

	return generators, nil
}

func genName(tag string) string {
	return fmt.Sprintf("generateV%sDefault",
		strings.ReplaceAll(strings.TrimPrefix(tag, "v"), ".", ""))
}

func generateReleaseGo(versions []Version) error {
	tmpl := `// This code is generated by scripts/versions_gen.go; DO NOT EDIT.
package profile

import (
	"github.com/EXBO-Community/stalcraft-jvm-optimization/internal/config"
	"github.com/EXBO-Community/stalcraft-jvm-optimization/internal/sysinfo"
)

var allVersions = []struct {
	Version     string
	Description string
	Generator   func(sysinfo.Info) config.Config
}{
	{{range $i, $v := .Versions}}
	{
		Version:     "{{$v.Tag}}",
		Description: "{{$v.Description}}",
		Generator:   {{$v.Generator}},
	},{{end}}
}

func versionToRelease(v struct {
	Version     string
	Description string
	Generator   func(sysinfo.Info) config.Config
}) Release {
	return Release{
		Version:       v.Version,
		Label:         v.Version,
		Description:   v.Description,
		DefaultPreset: "default",
		Presets: []Preset{
			{
				Name:     "default",
				Label:    "default",
				Generate: v.Generator,
			},
		},
	}
}

func Releases() []Release {
	out := make([]Release, len(allVersions))
	for i, v := range allVersions {
		out[i] = versionToRelease(v)
	}
	return out
}

func Find(version string) (Release, bool) {
	for _, v := range allVersions {
		if v.Version == version {
			return versionToRelease(v), true
		}
	}
	return Release{}, false
}

func Latest() Release {
	// allVersions is sorted newest-first due to --sort=-v:refname in git tag command
	return versionToRelease(allVersions[0])
}
`

	rootDir, err := findProjectRoot()
	if err != nil {
		return fmt.Errorf("failed to find project root: %w", err)
	}
	outputPath := filepath.Join(rootDir, "internal", "profile", "releases_generated.go")
	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	data := struct {
		Versions []Version
	}{
		Versions: versions,
	}

	t := template.Must(template.New("releases").Parse(tmpl))
	if err := t.Execute(f, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

func generateBuildinfoGo() error {
	cmd := exec.Command(
		"git",
		"describe",
		"--tags",
		"--always",
		"--dirty",
	)
	version, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("failed to get git version: %w", err)
	}

	cmd = exec.Command(
		"git",
		"rev-parse",
		"--short",
		"HEAD",
	)
	commit, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("failed to get git commit: %w", err)
	}

	tmpl := `// This code is generated by scripts/versions_gen.go; DO NOT EDIT.
package buildinfo

var (
	Version = "{{.Version}}"
	Commit  = "{{.Commit}}"
)
`

	rootDir, err := findProjectRoot()
	if err != nil {
		return fmt.Errorf("failed to find project root: %w", err)
	}
	outputPath := filepath.Join(rootDir, "internal", "buildinfo", "buildinfo_generated.go")
	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	data := struct {
		Version string
		Commit  string
	}{
		Version: strings.TrimSpace(string(version)),
		Commit:  strings.TrimSpace(string(commit)),
	}

	t := template.Must(template.New("buildinfo").Parse(tmpl))
	if err := t.Execute(f, data); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

func findProjectRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		goModPath := filepath.Join(dir, "go.mod")
		if _, err := os.Stat(goModPath); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}
